// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD02Wpf0jMl6cjnsfbx2epdEkQEaBKH64A',
    appId: '1:787989873030:web:09603db34685565f29ac07',
    messagingSenderId: '787989873030',
    projectId: 'gcp-f06-barcode',
    authDomain: 'gcp-f06-barcode.firebaseapp.com',
    storageBucket: 'gcp-f06-barcode.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02Wpf0jMl6cjnsfbx2epdEkQEaBKH64A',
    appId: '1:787989873030:android:d9495bc8845cdfa629ac07',
    messagingSenderId: '787989873030',
    projectId: 'gcp-f06-barcode',
    storageBucket: 'gcp-f06-barcode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhEjO9xX_MU5Fpy5ii9GoFUcm_kDnDlE',
    appId: '1:787989873030:ios:a5323fd3b038d99c29ac07',
    messagingSenderId: '787989873030',
    projectId: 'gcp-f06-barcode',
    storageBucket: 'gcp-f06-barcode.firebasestorage.app',
    iosBundleId: 'com.hackathon.f06.barcodeScanner',
  );
}
