// Mocks generated by Mockito 5.4.6 from annotations
// in barcode_scanner/test/features/auth/domain/usecases/sign_out_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:barcode_scanner/core/utils/result.dart' as _i4;
import 'package:barcode_scanner/features/auth/domain/entities/user.dart' as _i5;
import 'package:barcode_scanner/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User>> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<_i5.User>> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<_i5.User>> createAccount(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #createAccount,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<void>> resetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #resetPassword,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #sendEmailVerification,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Stream<_i5.User?> watchAuthStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #watchAuthStateChanges,
          [],
        ),
        returnValue: _i3.Stream<_i5.User?>.empty(),
      ) as _i3.Stream<_i5.User?>);

  @override
  _i3.Future<_i4.Result<_i5.User>> updateProfile({
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
            _i6.dummyValue<_i4.Result<_i5.User>>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<void>> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #updatePassword,
            [newPassword],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);
}
